# application.yml
server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:b2cdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/b2c-payment-realm

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.example.b2cpayment: DEBUG

